version: 2
jobs:
  build:
    branches:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKER_PASS | docker login --username sepiropht --password-stdin
      - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then cd server && docker build -t sepiropht/lireddit:$CIRCLE_BRANCH -f Dockerfile . --build-arg accessKeyId=$accessKeyId --build-arg SESSION_SECRET=$SESSION_SECRET --build-arg secretAccessKey=$secretAccessKey && docker push sepiropht/lireddit:$CIRCLE_BRANCH; fi
      - run: if [ "${CIRCLE_BRANCH}" != "master" ]; then cd server && docker build -t sepiropht/lireddit:$CIRCLE_BRANCH -f Dockerfile.dev . && docker push sepiropht/lireddit:$CIRCLE_BRANCH; fi

      - run: if [ "${CIRCLE_BRANCH}" != "master" ]; then ssh root@104.248.38.40 "docker pull sepiropht/lireddit:$CIRCLE_BRANCH && docker tag sepiropht/lireddit:$CIRCLE_BRANCH dokku/streamio-dev:$CIRCLE_BRANCH && dokku deploy streamio-dev $CIRCLE_BRANCH"; fi
      - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh root@104.248.38.40 "docker pull sepiropht/lireddit:$CIRCLE_BRANCH && docker tag sepiropht/lireddit:$CIRCLE_BRANCH dokku/api:$CIRCLE_BRANCH && dokku deploy api $CIRCLE_BRANCH"; fi
