version: '3'

services:
  db:
    container_name: adspy
    image: postgres:11.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

volumes:
  db_data:
